# Generated by Django 4.2 on 2023-04-16 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category_income_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 4, 16, 17, 7, 1, 651286, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 4, 16, 17, 7, 11, 415443, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
